version: '3.1'
services:
  web:
    image: odoo:14.0
    container_name: odoo14pel_web
    depends_on:
      - db
    ports:
      - "7779:8069"
    environment:
    - HOST=db
    - USER=odoo
    - PASSWORD=odoo
    volumes:
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/extra-addons
    command: --dev=all

  db:
    image: postgres:13
    container_name: postgres13_bd
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5439:5432"